export const CLIENT_AGENT_NAME = 'DDSM_AGENT';
export const CHANNELS = {
  FILTER_OPTIONS: 'FILTER_OPTIONS',
  ABNORMALITY_FILTER_OPTIONS: 'ABNORMALITY_FILTER_OPTIONS',
  PATIENTS: 'PATIENTS',
  PATIENT_DETAILS: 'PATIENT_DETAILS',
  PATIENT_IDS: 'PATIENT_IDS',
  PATIENT_IMAGES_DETAILS: 'PATIENT_IMAGES_DETAILS',
  PATIENT_IMAGE: 'PATIENT_IMAGE',
  CLOSE_WINDOW: 'CLOSE_WINDOW',
};
