export const CHANNELS = {
  FILTER_OPTIONS: 'FILTER_OPTIONS',
  ABNORMALITY_FILTER_OPTIONS: 'ABNORMALITY_FILTER_OPTIONS',
  PATIENT_IDS: 'PATIENT_IDS',
  PATIENT_IMAGES: 'PATIENT_IMAGES',
  CLOSE_WINDOW: 'CLOSE_WINDOW',
};
